# Generated by Django 5.1.7 on 2025-03-07 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('this_week_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('this_month_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('month', models.CharField(default='March', max_length=20)),
                ('website_name', models.CharField(default='', max_length=100)),
                ('weekly_updates', models.IntegerField(default=0)),
                ('monthly_updates', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_number', models.CharField(max_length=50)),
                ('withdraw_amount', models.CharField(max_length=50)),
                ('withdraw_method', models.CharField(max_length=50)),
                ('date_time', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
