# Generated by Django 5.1.7 on 2025-03-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='daily_updates',
            field=models.IntegerField(default=0),
        ),
    ]
