# Generated by Django 5.1.7 on 2025-03-08 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_userbalance_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
