# Generated by Django 5.1.7 on 2025-03-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userbalance_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='last_updated',
        ),
    ]
