# Generated by Django 5.1.7 on 2025-03-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_userbalance_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='website_name',
            field=models.CharField(default='NeonMonetization.com', max_length=100),
        ),
    ]
