# Generated by Django 5.1.7 on 2025-03-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_userbalance_website_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='website_name',
            field=models.CharField(default='neonmonetization.com', max_length=100),
        ),
    ]
